mod auto_add;
mod blocklist;
mod execute;
mod extractor;
mod label;
mod notifications;
mod scheduler;
mod stats;
mod toggle;
mod webui;

pub use auto_add::AutoAddClient;
pub use blocklist::BlocklistClient;
pub use execute::ExecuteClient;
pub use extractor::ExtractorClient;
pub use label::LabelClient;
pub use notifications::NotificationsClient;
pub use scheduler::SchedulerClient;
pub use stats::StatsClient;
pub use toggle::ToggleClient;
pub use webui::WebUiClient;
