name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    env:
      SCCACHE_GHA_ENABLED: "true"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: Mozilla-Actions/sccache-action@9e7fa8a12102821edf02ca5dbea1acd0f89a2696 # v0.0.10
      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
        with:
          toolchain: stable
      - name: Fmt
        run: cargo fmt --all --check
      - name: Check
        run: cargo check --workspace
      - name: Build
        run: cargo build --workspace
      - name: Lint
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings
      - name: Test
        run: cargo test --workspace --all-features --no-fail-fast
      - name: Doc
        run: RUSTDOCFLAGS="-D warnings" cargo doc --workspace --no-deps
